#!/bin/bash
# Quick Reference Card - ABI Snapshot Testing
# Copy-paste commands to get started

echo "═══════════════════════════════════════════════════════════════"
echo "ABI SNAPSHOT TESTING - QUICK REFERENCE"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📋 QUICK START"
echo "─────────────────────────────────────────────────────────────"
echo "1. Create feature branch:"
echo "   git checkout -b test/contract-frontend-abi-snapshots"
echo ""
echo "2. Verify files exist:"
echo "   ls build/contract-interface.snapshot.json"
echo "   ls frontend/src/contracts/__tests__/factoryAbi.snapshot.test.ts"
echo ""
echo "3. Run tests:"
echo "   cd frontend && npm run test:contracts:abi"
echo ""
echo "4. Run full CI:"
echo "   cd .. && ./scripts/ci-check.sh"
echo ""

echo "🚀 MOST COMMON COMMANDS"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Development:"
echo "  npm run test:contracts:abi              # Run once"
echo "  npm run test:contracts:abi:watch        # Watch mode"
echo "  npm run test:contracts:abi:update       # Update snapshot"
echo ""
echo "Generate Snapshot:"
echo "  node scripts/extract-contract-interface.js"
echo ""
echo "Full CI:"
echo "  ./scripts/ci-check.sh"
echo ""

echo "🔍 TEST SCENARIOS"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. Test Renamed Method:"
echo "   cp contracts/token-factory/src/lib.rs lib.rs.backup"
echo "   # Edit: change 'pub fn transfer_admin' to 'pub fn transfer_admin_renamed'"
echo "   node scripts/extract-contract-interface.js"
echo "   cd frontend && npm run test:contracts:abi"
echo "   # Expected: ❌ FAIL with 'method not found'"
echo "   mv lib.rs.backup contracts/token-factory/src/lib.rs"
echo ""
echo "2. Test Reordered Parameters:"
echo "   # Edit: swap parameters in 'pub fn burn(...)'"
echo "   node scripts/extract-contract-interface.js"
echo "   npm run test:contracts:abi"
echo "   # Expected: ❌ FAIL with parameter order mismatch"
echo ""
echo "3. Test New Method (Approved):"
echo "   # Add: pub fn my_new_feature(env: Env) -> bool { true }"
echo "   node scripts/extract-contract-interface.js"
echo "   npm run test:contracts:abi"
echo "   # Expected: ✓ PASS with 'Additive changes detected'"
echo ""

echo "📚 DOCUMENTATION"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Main Documentation:"
echo "  docs/ABI_SNAPSHOT_TESTING.md            # Full technical guide"
echo ""
echo "Implementation:"
echo "  IMPLEMENTATION_SUMMARY.md               # Quick reference"
echo "  FILES_CREATED_AND_MODIFIED.md           # File inventory"
echo ""
echo "Examples & Verification:"
echo "  frontend/src/contracts/__tests__/"
echo "    SNAPSHOT_TEST_SCENARIOS.md            # Example scenarios"
echo "  docs/VERIFY_ABI_SNAPSHOTS.sh            # Interactive verification"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "❓ \"Snapshot not found\""
echo "  → node scripts/extract-contract-interface.js"
echo ""
echo "❓ \"Method XXX not found\""
echo "  → Check if renamed: grep 'XXX' contracts/token-factory/src/lib.rs"
echo "  → Or update: frontend/src/contracts/factoryAbi.ts"
echo ""
echo "❓ \"Tests won't run\""
echo "  → cd frontend && npm install"
echo "  → npm run test:contracts:abi"
echo ""
echo "❓ \"Parameter count mismatch\""
echo "  → Check contract: grep -A 3 'pub fn method_name' contracts/token-factory/src/lib.rs"
echo "  → Update interface: frontend/src/contracts/factoryAbi.ts"
echo ""

echo "✅ VERIFICATION CHECKLIST"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "□ Snapshot file exists: build/contract-interface.snapshot.json"
echo "□ Test file exists: frontend/src/contracts/__tests__/factoryAbi.snapshot.test.ts"
echo "□ Tests pass: npm run test:contracts:abi"
echo "□ CI passes: ./scripts/ci-check.sh"
echo "□ Commits are logical"
echo "□ Branch name: test/contract-frontend-abi-snapshots"
echo "□ Ready to push and create PR"
echo ""

echo "🔗 FILES OVERVIEW"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Created:"
echo "  ✓ scripts/extract-contract-interface.js"
echo "  ✓ frontend/src/contracts/__tests__/factoryAbi.snapshot.test.ts"
echo "  ✓ contracts/token-factory/tests/interface_snapshot.rs"
echo "  ✓ build/contract-interface.snapshot.json (generated)"
echo "  ✓ docs/ABI_SNAPSHOT_TESTING.md"
echo "  ✓ docs/VERIFY_ABI_SNAPSHOTS.sh"
echo "  ✓ frontend/src/contracts/__tests__/SNAPSHOT_TEST_SCENARIOS.md"
echo ""
echo "Modified:"
echo "  ✏️  scripts/build-contract.sh"
echo "  ✏️  scripts/ci-check.sh"
echo "  ✏️  frontend/package.json"
echo ""

echo "💡 KEY INSIGHTS"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "✓ Detects breaking changes automatically"
echo "✓ Allows additive changes (new methods)"
echo "✓ Prevents silent ABI drift"
echo "✓ Integrated into CI pipeline"
echo "✓ < 1 second overhead in CI"
echo "✓ No production build impact"
echo "✓ Human-readable snapshots"
echo "✓ Easy to verify and review"
echo ""

echo "📖 READING ORDER"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "New to this feature? Read in order:"
echo "1. IMPLEMENTATION_SUMMARY.md               (2 min)"
echo "2. docs/ABI_SNAPSHOT_TESTING.md            (5 min)"
echo "3. SNAPSHOT_TEST_SCENARIOS.md              (3 min)"
echo "4. Run the tests yourself                  (1 min)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "Ready to start? Run:"
echo ""
echo "  git checkout -b test/contract-frontend-abi-snapshots"
echo "  ./scripts/ci-check.sh"
echo ""
echo "═══════════════════════════════════════════════════════════════"
